### PR TITLE
catch axios call

### LINKED ISSUE #7: Errors / Warning when building (found solution)
I got a lot of these when building:
````
(node:3018) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
````

I solved it by adding a `.catch()` where the axios call is for the search [here](https://github.com/drehimself/gridsome-portfolio-starter/blob/master/src/components/SearchInput.vue#L69). I just `console.log(error)`. Not sure if that is the best "solution".

The theme is still building so nothing is really "broken" here. Just wanted to let you know.

### PR DESCRIPTION
**Pull request by natedalliard**
Closes #7 .

### CODE REVIEW

File: src/components/SearchInput.vue [hunk 1]
```diff
@@ -67,6 +67,9 @@ export default {
     axios('/search.json').then(response => {
       this.posts = response.data
     })
+    .catch(function (error) {
```
Comment (drehimself) [inline src/components/SearchInput.vue]: Can you make it an arrow function to keep it consistent?

Comment (natedalliard) [reply src/components/SearchInput.vue]: Done.
